Repository JedWatson/react-select, pull requests merged in 2018-07, with the labels that each got.

#2724 [v2] Added makeAnimated factory for constructing animated components
  docs/examples/AnimatedMulti.js
  src/animated/Input.js
  src/animated/MultiValue.js
  src/animated/Placeholder.js
  src/animated/SingleValue.js
  src/animated/ValueContainer.js
  src/animated/index.js
  src/index.js
Labels: v2

#2581 [V2] live region implementation
  cypress/fixtures/selectors.json
  cypress/integration/select_spec.js
  docs/Tests.js
  src/Select.js
  src/__tests__/Select.test.js
  src/__tests__/__snapshots__/Async.test.js.snap
  src/__tests__/__snapshots__/AsyncCreatable.test.js.snap
  src/__tests__/__snapshots__/Select.test.js.snap
  src/accessibility/index.js
  src/components/Group.js
  src/components/Menu.js
  src/components/Option.js
  src/components/indicators.js
  src/primitives.js
  yarn.lock
Labels: v2

#2736 Always clear focusedOption when opening the menu
  src/Select.js
  test/Select-test.js
Labels: v1

#2704 Fix #1620
  src/Select.js
  test/Select-test.js
Labels: v1

#2465 Remain focused on option after selecting it
  src/Select.js
  test/Select-test.js
Labels: resolved in v2, v1

#1436 Add option to show new creatable item as first or last option
  README.md
  examples/src/components/Creatable.js
  src/Creatable.js
  test/Creatable-test.js
Labels: After 1.0 release

#2652 [v2] Re-render when defaultOptions changes
  src/Async.js
Labels: v2

#2767 [v2] Pressing <Enter> in IME mode should not select a option
  src/Select.js
Labels: v2

#2695 Change isOptionDisabled to have the same inputs as isOptionSelected
  docs/pages/upgradeGuide/index.js
  src/Select.js
Labels: needs review, uncertain, v2

#2821 [V2] Remove primitives and refactor MultiValue components
  docs/PropTypes/components/MultiValueContainer.js
  docs/PropTypes/components/MultiValueLabel.js
  docs/PropTypes/components/MultiValueRemove.js
  docs/examples/CustomIndicatorSeparator.js
  docs/examples/Experimental.js
  src/Select.js
  src/components/MultiValue.js
  src/internal/A11yText.js
  src/internal/ScrollBlock.js
  src/internal/index.js
  src/primitives.js
Labels: v2

#2818 v2 readme
  README.md
Labels: v2

#2820 remove deprecation warning and backward compatibility logic
  docs/Tests.js
  src/Select.js
Labels: v2

#2641 Prefer more descriptive esm word instead of es
  package.json
  rollup.config.js
Labels: v2
