Repository JedWatson/react-select, pull requests merged in 2020-08, with the labels that each got.

#3897 Fixes #3335 - removes the call to onMenuOpen within handleInputChange
  .changeset/thick-eyes-walk.md
  packages/react-select/src/Select.js
Labels: pr/enhancement, pr/in-review, pr/priority

#3904 Fix error when touches is not set
  packages/react-select/src/Select.js
Labels: pr/bug-fix, pr/in-review, pr/priority

#3928 Update MenuPlacer context usage to the new context API
  .changeset/update-context-api.md
  packages/react-select/src/components/Menu.js
Labels: pr/bug-fix, pr/in-review, pr/priority

#3964 A11yText DOM structure fix (breaking W3C validation)
  packages/react-select/src/Select.js
Labels: category/accessibility, pr/bug-fix, pr/in-review, pr/priority

#4048 Update README.md with React Hooks Example.
  README.md
Labels: category/documentation, pr/in-review, pr/priority
