Repository JedWatson/react-select, pull requests merged in 2020-12, with the labels that each got.

#4306 Update Creatable.js to remove duplicate entry
  .changeset/ten-apples-tap.md
  packages/react-select/src/Creatable.js
Labels: pr/needs-review, pr/priority, release/3.2

#4275 Adds react ^17.0.0 to peer dependencies for React 17 support
  .changeset/great-actors-end.md
  packages/react-select/package.json
Labels: pr/needs-review, release/3.2

#4084 [3055] prevent from passing different cx and getValue functions to children components when the results of those functions remain the same as previous render.
  .changeset/nasty-coats-fly.md
  packages/react-select/src/Select.js
Labels: pr/bug-fix, pr/in-review

#4154 Fix removing MultiValues that have identical values. Issue #4137
  .changeset/lazy-singers-applaud.md
  packages/react-select/src/Select.js
Labels: pr/bug-fix, pr/needs-review

#4213 protect against reading removeEventListener from el if null
  .changeset/lemon-boats-cover.md
  packages/react-select/src/internal/ScrollCaptor.js
Labels: pr/needs-review
