Repository JedWatson/react-select, pull requests merged in 2021-01, with the labels that each got.

#3990 Fix onCreateOption is not always called for Creatable
  .changeset/silver-cobras-attend.md
  packages/react-select/src/Select.js
Labels: pr/bug-fix, pr/in-review, pr/priority

#3046 Pass down extra props to group header as item.data
  packages/react-select/src/Select.js
Labels: pr/enhancement, pr/needs-review

#4329 4255: Check props to ensure Select not focused when isDisabled changed
  packages/react-select/src/Select.js
Labels: pr/bug-fix

#4136 Base aria-live message on tabSelectsValue prop
  .changeset/quick-carrots-count.md
  packages/react-select/src/Select.js
  packages/react-select/src/accessibility/index.js
Labels: pr/bug-fix, pr/needs-review

#4340 #3006: Documentation clarifications and Defining Components section
  docs/examples/CustomSelectProps.js
  docs/examples/index.js
  docs/pages/advanced/index.js
  docs/pages/components/index.js
  packages/react-select/src/Select.js
Labels: category/documentation

#4330 Resolve `findDOMNode` deprecation by merging `ScrollBlock` and `ScrollCaptor` into `ScrollManager`
  packages/react-select/src/Select.js
  packages/react-select/src/internal/NodeResolver.js
  packages/react-select/src/internal/ScrollBlock.js
  packages/react-select/src/internal/ScrollManager.js
  packages/react-select/src/internal/index.js
Labels: pr/menu

#4333 Refactor ScrollCaptor and ScrollLock into hooks
  .eslintrc.js
  docs/package.json
  package.json
  packages/react-select/src/internal/ScrollLock/constants.js
  packages/react-select/src/internal/ScrollLock/index.js
  packages/react-select/src/internal/ScrollLock/utils.js
  packages/react-select/src/internal/ScrollManager.js
  packages/react-select/src/internal/useScrollCapture.js
  packages/react-select/src/internal/useScrollLock.js
  yarn.lock
Labels: pr/menu

#4396 Fix key for options within groups
  .changeset/gorgeous-yaks-film.md
  packages/react-select/src/Select.js
Labels: pr/bug-fix, pr/priority
