Repository JedWatson/react-select, pull requests merged in 2021-03, with the labels that each got.

#4414 Aria Live Configuration
  .changeset/shaggy-chairs-poke.md
  docs/examples/CustomAriaLive.js
  docs/examples/index.js
  docs/pages/advanced/index.js
  packages/react-select/src/Select.js
  packages/react-select/src/__tests__/Select.test.js
  packages/react-select/src/__tests__/__snapshots__/Async.test.js.snap
  packages/react-select/src/__tests__/__snapshots__/AsyncCreatable.test.js.snap
  packages/react-select/src/__tests__/__snapshots__/Creatable.test.js.snap
  packages/react-select/src/__tests__/__snapshots__/Select.test.js.snap
  packages/react-select/src/__tests__/__snapshots__/StateManaged.test.js.snap
  packages/react-select/src/accessibility/index.js
  packages/react-select/src/components/LiveRegion.js
  packages/react-select/src/types.js
Labels: category/accessibility, category/documentation

#3827 Memoize strip diacritics for input
  .changeset/kind-yaks-clean.md
  packages/react-select/src/filters.js
Labels: pr/enhancement, pr/needs-review, pr/priority

#3875 Creatable: Add option meta field to onChange for 'create-option' action
  packages/react-select/src/Creatable.js
Labels: pr/enhancement, pr/needs-review

#4109 Replace componentWillReceiveProps with componentDidUpdate in docs and async component
  docs/App/Header.js
Labels: category/documentation, pr/bug-fix

#3262 Fix for Menu bottom is scrolled into view even when menuShouldScrollIntoView=false
  .changeset/fair-panthers-marry.md
  packages/react-select/src/components/Menu.js
Labels: pr/bug-fix, pr/in-review, pr/menu, pr/priority

#3360 Pass focusedOption to the MenuList
  .changeset/dirty-laws-trade.md
  packages/react-select/src/Select.js
  packages/react-select/src/components/Menu.js
Labels: pr/enhancement, pr/menu, pr/needs-review

#4480 Fix skipped unit tests for autoFocus and onChange
  packages/react-select/src/__tests__/Select.test.js
Labels: category/testing
